# Generated by Django 3.2 on 2024-06-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpaymentreceiptmaster',
            name='created_on_new',
        ),
        migrations.AlterField(
            model_name='tblcreditsnotesmaster',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tblcreditsnotesmaster',
            name='updated_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tblpaymentreceiptmaster',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tblpaymentreceiptmaster',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
